package ru.spring.core.project.statemachine;

public enum BotState {
    START,
    MODE_SELECTION,
    CURRENT_WEATHER_ENTER_CITY,
    AWAITING_CITY_NAME,
    FULL_WEATHER_FORECAST,
    WEATHER_ENTER_CITY,
    USER_ENTER_LOCATION_ONE,
    USER_ENTER_LOCATION_TWO,
    USER_ENTER_LOCATION_FIVE,
    FORECAST_AWAITING_CITY_NAME_DAY,
    FORECAST_AWAITING_CITY_NAME_TWO_DAYS,
    FORECAST_AWAITING_CITY_NAME_FIVE_DAYS
}